export type IntegrationStatus = "live" | "coming-soon" | "on-request";

export interface Integration {
  id: string;
  name: string;
  category: string;
  description: string;
  status: IntegrationStatus;
  logoSlug: string;
}

export const INTEGRATIONS: Integration[] = [
  {
    id: "quickbooks-online",
    name: "QuickBooks Online",
    category: "Accounting & ERP",
    description: "Sync payments → revenue, fees → expense.",
    status: "live",
    logoSlug: "quickbooks-online",
  },
  {
    id: "xero",
    name: "Xero",
    category: "Accounting & ERP",
    description: "Same.",
    status: "live",
    logoSlug: "xero",
  },
  {
    id: "netsuite",
    name: "NetSuite",
    category: "Accounting & ERP",
    description: "Full GL sync, multi-entity, multi-currency.",
    status: "coming-soon",
    logoSlug: "netsuite",
  },
  {
    id: "sage-intacct",
    name: "Sage Intacct",
    category: "Accounting & ERP",
    description: "Coming soon.",
    status: "coming-soon",
    logoSlug: "sage-intacct",
  },
  {
    id: "modern-treasury",
    name: "Modern Treasury",
    category: "Treasury & Finance",
    description: "Payouts orchestration + bank rail abstraction.",
    status: "live",
    logoSlug: "modern-treasury",
  },
  {
    id: "mercury",
    name: "Mercury",
    category: "Treasury & Finance",
    description: "Settlement balance sync.",
    status: "coming-soon",
    logoSlug: "mercury",
  },
  {
    id: "brex",
    name: "Brex",
    category: "Treasury & Finance",
    description: "Card spend sync.",
    status: "coming-soon",
    logoSlug: "brex",
  },
  {
    id: "stripe-billing",
    name: "Stripe Billing",
    category: "Billing & Subscriptions",
    description: "Useroutr handles settlement, Stripe handles subscriptions.",
    status: "live",
    logoSlug: "stripe-billing",
  },
  {
    id: "chargebee",
    name: "Chargebee",
    category: "Billing & Subscriptions",
    description: "Webhook bridge for renewal events.",
    status: "live",
    logoSlug: "chargebee",
  },
  {
    id: "recurly",
    name: "Recurly",
    category: "Billing & Subscriptions",
    description: "Request access.",
    status: "on-request",
    logoSlug: "recurly",
  },
  {
    id: "maxio",
    name: "Maxio",
    category: "Billing & Subscriptions",
    description: "Request access.",
    status: "on-request",
    logoSlug: "maxio",
  },
  {
    id: "segment",
    name: "Segment",
    category: "Customer Data & Analytics",
    description: "Stream payment events to anywhere.",
    status: "live",
    logoSlug: "segment",
  },
  {
    id: "mixpanel-amplitude",
    name: "Mixpanel / Amplitude",
    category: "Customer Data & Analytics",
    description: "Pre-built event mappings.",
    status: "live",
    logoSlug: "mixpanel-amplitude",
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "Customer Data & Analytics",
    description: "Open-source bridge.",
    status: "live",
    logoSlug: "posthog",
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "Support & Success",
    description: "Pull payment + dispute context into customer conversations.",
    status: "live",
    logoSlug: "intercom",
  },
  {
    id: "zendesk",
    name: "Zendesk",
    category: "Support & Success",
    description: "Same.",
    status: "live",
    logoSlug: "zendesk",
  },
  {
    id: "front",
    name: "Front",
    category: "Support & Success",
    description: "Same.",
    status: "live",
    logoSlug: "front",
  },
  {
    id: "linear",
    name: "Linear",
    category: "Dev Tools",
    description: "Open issues from failed webhooks.",
    status: "live",
    logoSlug: "linear",
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    category: "Dev Tools",
    description: "Pager on /readyz alerts.",
    status: "live",
    logoSlug: "pagerduty",
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "Dev Tools",
    description: "Auto-attach Useroutr request IDs.",
    status: "live",
    logoSlug: "sentry",
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "Dev Tools",
    description: "Metrics + trace correlation.",
    status: "live",
    logoSlug: "datadog",
  },
];
